cnn_layers: 152
detect_thresh: 2.51511e-05
loss: fp_penalty
max_offset: 5.0
metal: CD
plm: esm2_t33_650M_UR50D
pretrained_rnn: checkpoints/seq_predictors/CD.ckpt
rnn_hidden_size: 256
rnn_layers: 3
rnn_type: gru
