cnn_layers: 152
detect_thresh: 1.4492195e-05
loss: fp_penalty
max_offset: 5.0
metal: MN
plm: esm2_t33_650M_UR50D
pretrained_rnn: checkpoints/seq_predictors/MN.ckpt
rnn_hidden_size: 256
rnn_layers: 3
rnn_type: gru
