cnn_layers: 152
detect_thresh: 7.136734e-05
loss: fp_penalty
max_offset: 3.0
metal: ZN
plm: esm2_t33_650M_UR50D
pretrained_rnn: checkpoints/seq_predictors/ZN.ckpt
rnn_hidden_size: 256
rnn_layers: 3
rnn_type: gru
